#!/usr/bin/env bash


declare -a dirs=("alacritty" "amethyst" "bin" "config" "fzf" "tmux" "vim" "zsh")

for dir in "${dirs[@]}"
do
    echo "Stowing $dir"
    stow --restow --target=$HOME "$dir"
done
