#!/usr/bin/env bash

declare -a dirs=("alacritty" "amethyst" "bin" "config" "fzf" "tmux" "vim" "zsh")

for dir in "${dirs[@]}"
do
    echo "Unstowing $dir"
    stow --delete --target=$HOME "$dir"
done
